export const cursosBolivia = [
  { value: "1° primaria", label: "1° de Primaria" },
  { value: "2° primaria", label: "2° de Primaria" },
  { value: "3° primaria", label: "3° de Primaria" },
  { value: "4° primaria", label: "4° de Primaria" },
  { value: "5° primaria", label: "5° de Primaria" },
  { value: "6° primaria", label: "6° de Primaria" },
  { value: "1° secundaria", label: "1° de Secundaria" },
  { value: "2° secundaria", label: "2° de Secundaria" },
  { value: "3° secundaria", label: "3° de Secundaria" },
  { value: "4° secundaria", label: "4° de Secundaria" },
  { value: "5° secundaria", label: "5° de Secundaria" },
  { value: "6° secundaria", label: "6° de Secundaria" },
];

export const departamentosBolivia = [
  { value: "Chuquisaca", label: "Chuquisaca" },
  { value: "La Paz", label: "La Paz" },
  { value: "Cochabamba", label: "Cochabamba" },
  { value: "Oruro", label: "Oruro" },
  { value: "Potosí", label: "Potosí" },
  { value: "Tarija", label: "Tarija" },
  { value: "Santa Cruz", label: "Santa Cruz" },
  { value: "Beni", label: "Beni" },
  { value: "Pando", label: "Pando" },
];

export const provinciasPorDepartamento = {
  "La Paz": [
    { label: "Abel Iturralde", value: "Abel Iturralde" },
    { label: "Aroma", value: "Aroma" },
    { label: "Bautista Saavedra", value: "Bautista Saavedra" },
    { label: "Caranavi", value: "Caranavi" },
    { label: "Eliodoro Camacho", value: "Eliodoro Camacho" },
    { label: "Franz Tamayo", value: "Franz Tamayo" },
    { label: "Gualberto Villarroel", value: "Gualberto Villarroel" },
    { label: "Ingavi", value: "Ingavi" },
    { label: "Inquisivi", value: "Inquisivi" },
    { label: "José Manuel Pando", value: "José Manuel Pando" },
    { label: "Larecaja", value: "Larecaja" },
    { label: "Loayza", value: "Loayza" },
    { label: "Los Andes", value: "Los Andes" },
    { label: "Murillo", value: "Murillo" },
    { label: "Muñecas", value: "Muñecas" },
    { label: "Nor Yungas", value: "Nor Yungas" },
    { label: "Omasuyos", value: "Omasuyos" },
    { label: "Pacajes", value: "Pacajes" },
    { label: "Sud Yungas", value: "Sud Yungas" },
  ],
  Cochabamba: [
    { label: "Arani", value: "Arani" },
    { label: "Ayopaya", value: "Ayopaya" },
    { label: "Bolívar", value: "Bolívar" },
    { label: "Capinota", value: "Capinota" },
    { label: "Carrasco", value: "Carrasco" },
    { label: "Cercado", value: "Cercado" },
    { label: "Chapare", value: "Chapare" },
    { label: "Esteban Arce", value: "Esteban Arce" },
    { label: "Germán Jordán", value: "Germán Jordán" },
    { label: "Mizque", value: "Mizque" },
    { label: "Narciso Campero", value: "Narciso Campero" },
    { label: "Punata", value: "Punata" },
    { label: "Quillacollo", value: "Quillacollo" },
    { label: "Tapacarí", value: "Tapacarí" },
    { label: "Tiraque", value: "Tiraque" },
  ],
  "Santa Cruz": [
    { label: "Andrés Ibáñez", value: "Andrés Ibáñez" },
    { label: "Ángel Sandóval", value: "Ángel Sandóval" },
    { label: "Chiquitos", value: "Chiquitos" },
    { label: "Cordillera", value: "Cordillera" },
    { label: "Florida", value: "Florida" },
    { label: "Germán Busch", value: "Germán Busch" },
    { label: "Guarayos", value: "Guarayos" },
    { label: "Ichilo", value: "Ichilo" },
    { label: "Ignacio Warnes", value: "Ignacio Warnes" },
    { label: "José Miguel de Velasco", value: "José Miguel de Velasco" },
    { label: "Manuel María Caballero", value: "Manuel María Caballero" },
    { label: "Obispo Santistevan", value: "Obispo Santistevan" },
    { label: "Sara", value: "Sara" },
    { label: "Vallegrande", value: "Vallegrande" },
  ],
  Oruro: [
    { label: "Atahuallpa", value: "Atahuallpa" },
    { label: "Carangas", value: "Carangas" },
    { label: "Cercado", value: "Cercado" },
    { label: "Eduardo Avaroa", value: "Eduardo Avaroa" },
    { label: "Ladislao Cabrera", value: "Ladislao Cabrera" },
    { label: "Litoral", value: "Litoral" },
    { label: "Mejillones", value: "Mejillones" },
    { label: "Nor Carangas", value: "Nor Carangas" },
    { label: "Pantaleón Dalence", value: "Pantaleón Dalence" },
    { label: "Poopó", value: "Poopó" },
    { label: "Sabaya", value: "Sabaya" },
    { label: "San Pedro de Totora", value: "San Pedro de Totora" },
    { label: "Sajama", value: "Sajama" },
    { label: "Sebastián Pagador", value: "Sebastián Pagador" },
    { label: "Sud Carangas", value: "Sud Carangas" },
    { label: "Tomás Barrón", value: "Tomás Barrón" },
  ],
  Potosí: [
    { label: "Alonso de Ibáñez", value: "Alonso de Ibáñez" },
    { label: "Antonio Quijarro", value: "Antonio Quijarro" },
    { label: "Bernardino Bilbao", value: "Bernardino Bilbao" },
    { label: "Charcas", value: "Charcas" },
    { label: "Chayanta", value: "Chayanta" },
    { label: "Cornelio Saavedra", value: "Cornelio Saavedra" },
    { label: "Daniel Campos", value: "Daniel Campos" },
    { label: "Enrique Baldivieso", value: "Enrique Baldivieso" },
    { label: "José María Linares", value: "José María Linares" },
    { label: "Modesto Omiste", value: "Modesto Omiste" },
    { label: "Nor Chichas", value: "Nor Chichas" },
    { label: "Nor Lípez", value: "Nor Lípez" },
    { label: "Rafael Bustillo", value: "Rafael Bustillo" },
    { label: "Sur Chichas", value: "Sur Chichas" },
    { label: "Sur Lípez", value: "Sur Lípez" },
    { label: "Tomás Frías", value: "Tomás Frías" },
  ],
  Chuquisaca: [
    { label: "Azurduy", value: "Azurduy" },
    { label: "Belisario Boeto", value: "Belisario Boeto" },
    {
      label: "Chuquisaca Centro (Oropeza)",
      value: "Chuquisaca Centro (Oropeza)",
    },
    { label: "Hernando Siles", value: "Hernando Siles" },
    { label: "Jaime Zudáñez", value: "Jaime Zudáñez" },
    { label: "Luis Calvo", value: "Luis Calvo" },
    { label: "Nor Cinti", value: "Nor Cinti" },
    { label: "Sud Cinti", value: "Sud Cinti" },
    { label: "Tomina", value: "Tomina" },
    { label: "Yamparáez", value: "Yamparáez" },
  ],
  Tarija: [
    { label: "Aniceto Arce", value: "Aniceto Arce" },
    { label: "Burnet O'Connor", value: "Burnet O'Connor" },
    { label: "Cercado", value: "Cercado" },
    { label: "Eustaquio Méndez", value: "Eustaquio Méndez" },
    { label: "Gran Chaco", value: "Gran Chaco" },
    { label: "José María Avilés", value: "José María Avilés" },
  ],
  Beni: [
    { label: "Cercado", value: "Cercado" },
    { label: "Iténez", value: "Iténez" },
    { label: "José Ballivián", value: "José Ballivián" },
    { label: "Mamoré", value: "Mamoré" },
    { label: "Marbán", value: "Marbán" },
    { label: "Moxos", value: "Moxos" },
    { label: "Vaca Díez", value: "Vaca Díez" },
    { label: "Yacuma", value: "Yacuma" },
  ],
  Pando: [
    { label: "Abuná", value: "Abuná" },
    { label: "Federico Román", value: "Federico Román" },
    { label: "Madre de Dios", value: "Madre de Dios" },
    { label: "Manuripi", value: "Manuripi" },
    { label: "Nicolás Suárez", value: "Nicolás Suárez" },
  ],
};
