export const cursosBolivia = [
  { value: "primaria_1", label: "1° de Primaria" },
  { value: "primaria_2", label: "2° de Primaria" },
  { value: "primaria_3", label: "3° de Primaria" },
  { value: "primaria_4", label: "4° de Primaria" },
  { value: "primaria_5", label: "5° de Primaria" },
  { value: "primaria_6", label: "6° de Primaria" },
  { value: "secundaria_1", label: "1° de Secundaria" },
  { value: "secundaria_2", label: "2° de Secundaria" },
  { value: "secundaria_3", label: "3° de Secundaria" },
  { value: "secundaria_4", label: "4° de Secundaria" },
  { value: "secundaria_5", label: "5° de Secundaria" },
  { value: "secundaria_6", label: "6° de Secundaria" },
];

export const departamentosBolivia = [
  { value: "chuquisaca", label: "Chuquisaca" },
  { value: "la_paz", label: "La Paz" },
  { value: "cochabamba", label: "Cochabamba" },
  { value: "oruro", label: "Oruro" },
  { value: "potosi", label: "Potosí" },
  { value: "tarija", label: "Tarija" },
  { value: "santa_cruz", label: "Santa Cruz" },
  { value: "beni", label: "Beni" },
  { value: "pando", label: "Pando" },
];

export const areasDeInteres = [
  { value: "astronomia", label: "ASTRONOMÍA - ASTROFÍSICA" },
  { value: "biologia", label: "BIOLOGÍA" },
  { value: "fisica", label: "FÍSICA" },
  { value: "informatica", label: "INFORMÁTICA" },
  { value: "matematicas", label: "MATEMÁTICAS" },
  { value: "quimica", label: "QUÍMICA" },
  { value: "robotica", label: "ROBÓTICA" },
];

export const categorias = [
  { value: "3p", label: "3P - 3ro Primaria" },
  { value: "4p", label: "4P - 4to Primaria" },
  { value: "5p", label: "5P - 5to Primaria" },
  { value: "6p", label: "6P - 6to Primaria" },
  { value: "1s", label: "1S - 1ro Secundaria" },
  { value: "2s", label: "2S - 2do Secundaria" },
  { value: "3s", label: "3S - 3ro Secundaria" },
  { value: "4s", label: "4S - 4to Secundaria" },
  { value: "5s", label: "5S - 5to Secundaria" },
  { value: "6s", label: "6S - 6to Secundaria" },
  { value: "guacamayo", label: "Guacamayo - 5to a 6to Primaria" },
  { value: "guanaco", label: "Guanaco - 1ro a 3ro Secundaria" },
  { value: "londra", label: "Londra - 1ro a 3ro Secundaria" },
  { value: "jucumari", label: "Jucumari - 4to a 6to Secundaria" },
  { value: "bufeo", label: "Bufeo - 1ro a 3ro Secundaria" },
  { value: "puma", label: "Puma - 4to a 6to Secundaria" },
  { value: "primer_nivel", label: "Primer Nivel - 1ro Secundaria" },
  { value: "segundo_nivel", label: "Segundo Nivel - 2do Secundaria" },
  { value: "tercer_nivel", label: "Tercer Nivel - 3ro Secundaria" },
  { value: "cuarto_nivel", label: "Cuarto Nivel - 4to Secundaria" },
  { value: "quinto_nivel", label: "Quinto Nivel - 5to Secundaria" },
  { value: "sexto_nivel", label: "Sexto Nivel - 6to Secundaria" },
  { value: "builders_p", label: "Builders P - 5to a 6to Primaria" },
  { value: "builders_s", label: "Builders S - 1ro a 6to Secundaria" },
  { value: "lego_p", label: "Lego P - 5to a 6to Primaria" },
  { value: "lego_s", label: "Lego S - 1ro a 6to Secundaria" },
];
